### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by adahiroOno** [adahiroOno/support_frontend_for_dearhero#1]
① 開発環境構築
  - [x] リポジトリ作成
  - [x] コンパイル環境作成
  - [x] CSS設計
    - [x] ルール決め
    -  [x] ベースの作成
      - [x] 変数、メディアクエリ、リセットcss

**Comment by Sadahiro-0no** [comment]
BEMディレクトリ構成
基本は下記の構成に従う。
```
cssフォルダ
scssフォルダ：Sassファイル群
base：リセットとサイト共通定義
_base.scss：サイト共通定義
_reset.scss：リセットCSS <= style.scssで定義済み
mixinフォルダ：サイト内で何度も使うデザイン定義群
_btn.scss：ボタンデザイン
_font.scss：書体関係デザイン
_form.scss：フォームデザイン
_media.scss：メディアクエリ
_other.scss：その他
moduleフォルダ：ブロック（パーツ）単位のSCSSファイル群
_ブロック名.scss：
page：ページ専用CSSが必要な時に使用するファイル群
index.scss：トップページ専用デザイン定義
setting：変数管理ファイル群
_config.scss：サイト共通変数
style.scss：使用するSCSSをインポートするファイル
書き出されるCSS.css
```
参考: https://jobtech.jp/html_css/4245/

**Comment by Sadahiro-0no** [comment]
scss自動コンパイル参考
https://qiita.com/mimimi-no-sesese/items/bbaab077d179c7ca415d
https://webrandum.net/npm-script-sass-compile/

**Comment by Sadahiro-0no** [comment]
Q.ベース・変数・メディアクエリのあたりって、どうやって定義している？
HTML側の実装ない状態でのCSSを記述できるイメージが今沸かなくて、どういうプロセスでCSS書いてる？

A.
```
デザインをみて、こんな感じで考えて設定してる！
base.scss
↓
全体で使ってるfont-family、font-size、font-colorなどをbodyタグに設定しておく
例：
body {
  font-size: 15px;
  font-family: YuMincho, 'Yu Mincho', serif;
  font-weight: 400;
  letter-spacing: 0.1em;
  color: $black;
  @include mq() {
    font-size: vw_sp(28);
  }
}
変数
↓
とりあえず色は変数にしておくかな、これもデザイン見て用意しておくと良い
他にもいろんな場所で呼び出すものは変数にするけどそれは後からでもいいかも
例：
$pc-width: 1440;
$pc-main-width: 1268;
$pc-sub-width: 1096;
$pc-menu-width: 172;
$ease-in-cubic: cubic-bezier(0.55,0.08,0.68,0.53);
// colors
$white: #ffffff;
$black: #111111;
$gray: #EFEFEF;
$gray-light: #F9F9F9;
メディアクエリは、さっきのmixin関数使ってる！
基本的には768pxでPCとSPを切り替えるメディアクエリしか使わない！
```

**Comment by Sadahiro-0no** [comment]
SCSS　おすすめ関数
@mixin mq($point: mobile) {
  @if $point==desktop {
    @media (min-width: 768px) {
      @content;
    }
  }
  @if $point==tablet {
    @media (min-width: 768px) and (max-width: 1025px) {
      @content;
    }
  }
  @if $point==desktop-large {
    @media (min-width: 1440px) {
      @content;
    }
  }
  @if $point==mobile {
    @media (max-width: 767px) {
      @content;
    }
  }
  @if $point==small-mobile {
    @media (max-width: 350px) {
      @content;
    }
  }
  @if $point==landscape {
    @media (max-width: 767px) and (orientation: landscape) {
      @content;
    }
  }
}
こんな感じでメディアクエリを簡易化して書ける！
.header {
// pc
@include mq(desktop) {
  font-size: 20px;
}
// sp
@include mq() {
  font-size: 16px;
}
}

**Comment by Sadahiro-0no** [comment]
ress cssは、 npmでインストール

**Comment by Sadahiro-0no** [comment]
メディアクエリ参考
https://www.tam-tam.co.jp/tipsnote/html_css/post10708.html
